name: Force Pages redeploy

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  redeploy:
    name: Redeploy Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
